### ISSUE TITLE
fix introduction monologue

### ISSUE THREAD

**Issue by danieleguido** [C2DH/zoomland#18]

**Comment by florentina-a** [comment]
Hello,

After the exchanges that I had yesterday with Daniele via Slack and with Sarah Cooper, I would propose:
- to shorten a bit the noisy part of the intro (after pressing the Read Book button);
- to replace the first three sentences from the intro monologue "It broke, again. So… Can we actually trust the digital? I’ll go for the Source." by the following two sentences: “This version of the book seems broken ! I'll search for the original.”
This because it may be unclear for the players what is the Source, and also because it may be a contradiction between the idea of not trusting the digital and the fact that the player is finally directed to a digital version of the book.

We will have soon Sarah's comments for the English proofreading that I will share with you.

Thank you!
